# Generated by Django 4.2.20 on 2025-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='experience_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='experiences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
