# Generated by Django 4.2.20 on 2025-06-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hairdresser_experience_time_hairdresser_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
