# Generated by Django 5.1.4 on 2025-04-26 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0002_initial'),
        ('service', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer')),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='review.review')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.service')),
            ],
        ),
    ]
