# Generated by Django 4.2.20 on 2025-04-19 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='preferences_pictures/')),
                ('user_id', models.ManyToManyField(related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
