# Generated by Django 4.2.20 on 2025-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='user_id',
            new_name='users',
        ),
    ]
