# Generated by Django 5.1.4 on 2025-04-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_rename_user_id_preferences_users'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='services',
            field=models.ManyToManyField(related_name='preferences', to='service.service'),
        ),
    ]
