# Generated by Django 5.1.4 on 2025-04-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.PositiveSmallIntegerField()),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.hairdresser')),
            ],
        ),
    ]
