# Generated by Django 4.2.20 on 2025-04-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='hairdresser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.hairdresser'),
        ),
    ]
