# Generated by Django 5.1.4 on 2025-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
